package main

// Album represents a record album with ID, title, artist, and price.
// The ID is generated by the server and ignored if provided by the client.
type Album struct {
	ID     string  `json:"id"`
	Title  string  `json:"title"`
	Artist string  `json:"artist"`
	Price  float64 `json:"price"`
}

// albums stores the collection of albums in memory.
// In production, this would be stored in a database.
var albums = []Album{
	{ID: "550e8400-e29b-41d4-a716-446655440001", Title: "Blue Train", Artist: "John Coltrane", Price: 56.99},
	{ID: "550e8400-e29b-41d4-a716-446655440002", Title: "Jeru", Artist: "Gerry Mulligan", Price: 17.99},
	{ID: "550e8400-e29b-41d4-a716-446655440003", Title: "Sarah Vaughan and Clifford Brown", Artist: "Sarah Vaughan", Price: 39.99},
}
